### ISSUE TITLE
异常情况提出

### ISSUE THREAD

**Issue by ZZ0YY** [f4team-cn/f4pan#10]
个别账号存在在手机端抓取到完整登录 cookie 添加后，添加成功，但是用来解析有 98 的概率提示创建文件夹失败 响应的 code 值为 200，并无异常，但是结果无直链

使用手机端 App 对分享链接进行转存并下载并无异常

于是使用扫码添加，或许是因为扫码添加是电脑端？，添加成功后能够正常解析

ps：仅仅为个别账号，其他账号使用手机端抓取的 cookie 并无异常

**Comment by Yincmewy** [comment]
手机抓包cookie可能不完整，尝试使用`隐私模式`进行抓包，建议使用项目提供的`扫码登陆`功能添加账号
