### ISSUE TITLE
无法加入群组

### ISSUE THREAD

**Issue by xiaoxiongweihu** [f4team-cn/f4pan#12]

**Comment by swim233** [comment]
@xiaoxiongweihu 请附上你的username或TelegramID

**Comment by xiaoxiongweihu** [comment]
彭于晏 用户名@S0kane

**Comment by xiaoxiongweihu** [comment]
@swim233 彭于晏 用户名@S0kane

**Comment by swim233** [comment]
@xiaoxiongweihu 看了一下没看到相关记录 重新尝试加群 检查有没有验证bot私聊你

**Comment by xiaoxiongweihu** [comment]
@swim233 尝试重新加群，就显示这个
![image](https://github.com/user-attachments/assets/744e37f3-8cd8-4632-9ff1-42b9194d6d84)
这个是机器人所有私聊内容
![image](https://github.com/user-attachments/assets/8717cb84-a250-43e9-b963-009160810ad1)

**Comment by swim233** [comment]
不是这个bot 是 @NeoAuthBot



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月10日 15:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [f4team-cn/f4pan] 无法加入群组 (Issue #12) |

@swim233 尝试重新加群，就显示这个
image.png (view on web)
这个是机器人所有私聊内容
image.png (view on web)

**Comment by xiaoxiongweihu** [comment]
@swim233 没有过
![image](https://github.com/user-attachments/assets/13974cfa-49e5-42e7-a0a7-122c08ef9273)

**Comment by swim233** [comment]
@xiaoxiongweihu 那你等会 过会处理
