### ISSUE TITLE
更新后从 main 拉取文件，依旧存在PHP版本＞8.0 限制

### ISSUE THREAD

**Issue by ZZ0YY** [f4team-cn/f4pan#13]
Problem 1
    - symfony/var-dumper is locked to version v6.3.1 and an update of this package was not requested.
    - symfony/var-dumper v6.3.1 requires php >=8.1 -> your php version (8.0.26) does not satisfy that requirement.

只不过不是之前的那个 install.php 都限制

**Comment by Yincmewy** [comment]
那就换8.1

**Comment by ZZ0YY** [comment]
是否有对其进行降级操作的可能？symfony/var-dumper
服务器内存不足 PHP版本难以升级

**Comment by Yincmewy** [comment]
没有

**Comment by Yincmewy** [comment]
可自行尝试降级，我不建议进行降级操作，可能会导致预期之外的问题

**Comment by ZZ0YY** [comment]
那最好项目说明的 PHP版本限制最好修改一下

**Comment by Yincmewy** [comment]
> 那最好项目说明的 PHP版本限制最好修改一下

下个版本会更改php版本限制
