### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by AGZZY11** [f4team-cn/f4pan#14]
所有的环境都满足了，为什么安装后自动跳到环境检查界面，说有问题
![image](https://github.com/user-attachments/assets/e6cbf606-8dfb-452b-b144-8b6c33791095)
![image](https://github.com/user-attachments/assets/475adc96-0ba2-48df-9097-52ab5feee55d)
![image](https://github.com/user-attachments/assets/8b65505a-ee74-443f-a291-0995c48df03b)

**Comment by Yincmewy** [comment]
可能是Cookie过长，请**清空**数据库后，重试
缩短Cookie只留下BDUSS和STOKEN即可

如果尝试后仍然不可安装，请在**根目录**新建一个`.env`文件写入`APP_DEBUG=true`后**清空**数据库打开f12抓取`install`接口的返回内容回复到此议题下

**Comment by AGZZY11** [comment]
十分感谢，安装成功了
![c56fdec3350594089be8ed6e8a31eb2](https://github.com/user-attachments/assets/e13ace22-bdb9-4bd3-b42b-770fb6602beb)
但我在请求这个接口时显示500错误，是我的配置有问题吗
![image](https://github.com/user-attachments/assets/fe606fff-bfc0-4317-811c-48e492e287e3)

**Comment by Yincmewy** [comment]
我需要开启debug后的响应体

**Comment by AGZZY11** [comment]
[console.log](https://github.com/user-attachments/files/16569610/console.log)

**Comment by AGZZY11** [comment]
成功了，感谢指点
