### ISSUE TITLE
关于动态密码的获取方式

### ISSUE THREAD

**Issue by ZZ0YY** [f4team-cn/f4pan#15]
似乎无法获取，已经添加密钥![mmexport1723289955380.png](https://github.com/user-attachments/assets/95c1216b-b9ea-452e-84ac-58f901a3da8c)

![mmexport1723289958942.png](https://github.com/user-attachments/assets/a9432324-1216-4579-a418-7724cfb2ab7b)

![mmexport1723289957143.png](https://github.com/user-attachments/assets/659798ab-df5b-4710-b0ab-1de4c3058b32)

**Comment by Yincmewy** [comment]
把{apikey}改成那个后台的字符串f4pan_apikey_xxxxxx

**Comment by yangjiaji1795** [comment]
@Yincmewy ![屏幕截图 2024-08-14 012323](https://github.com/user-attachments/assets/31df7235-c5f2-47ca-9cfb-b34b63f873b9)
![屏幕截图 2024-08-14 012343](https://github.com/user-attachments/assets/fbe0def8-ae71-4414-aa28-93f61e00b6a0)
那我这种的怎么解决

**Comment by Yincmewy** [comment]
> @Yincmewy ![屏幕截图 2024-08-14 012323](https://github.com/user-attachments/assets/31df7235-c5f2-47ca-9cfb-b34b63f873b9)
> ![屏幕截图 2024-08-14 012343](https://github.com/user-attachments/assets/fbe0def8-ae71-4414-aa28-93f61e00b6a0)
> 那我这种的怎么解决

目测没有连接上redis，可能是设置了密码
详细的错误需要在`.env`文件中写入`APP_DEBUG=true`后重新访问此页面才能确定

**Comment by yangjiaji1795** [comment]
看了是redis的问题但是不知道怎么改

**Comment by yangjiaji1795** [comment]
@Yincmewy ![image](https://github.com/user-attachments/assets/bf183390-431c-4a44-bba0-e7efe13b4ae9)
重新安装测试是过的

**Comment by Yincmewy** [comment]
> @Yincmewy ![image](https://github.com/user-attachments/assets/bf183390-431c-4a44-bba0-e7efe13b4ae9)
> 重新安装测试是过的
> 

截图开启debug后的页面报错

**Comment by yangjiaji1795** [comment]
![image](https://github.com/user-attachments/assets/0c0e10f0-5d19-46eb-89e7-79a9b85b73a5)

**Comment by yangjiaji1795** [comment]
> > @Yincmewy ![image](https://private-user-images.githubusercontent.com/73827879/357520004-bf183390-431c-4a44-bba0-e7efe13b4ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzI4MDcsIm5iZiI6MTcyMzU3MjUwNywicGF0aCI6Ii83MzgyNzg3OS8zNTc1MjAwMDQtYmYxODMzOTAtNDMxYy00YTQ0LWJiYTAtZTdlZmUxM2I0YWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE4MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMzRlMmRjMDJiZjEyZmJiOTMwNzRmYTllZGM2YzFjMDM5YTg1NTVmYjIxMDFmNTJlMWM1ZWE1MDA1ODI4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8Cp1N8hfH0qWe_JX7zCdp16fiNB4BdrMDHchnHOFKs)
> > 重新安装测试是过的
> 
> 截图开启debug后的页面报错

你看看怎么个事

**Comment by Yincmewy** [comment]
> > > @Yincmewy ![image](https://private-user-images.githubusercontent.com/73827879/357520004-bf183390-431c-4a44-bba0-e7efe13b4ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzI4MDcsIm5iZiI6MTcyMzU3MjUwNywicGF0aCI6Ii83MzgyNzg3OS8zNTc1MjAwMDQtYmYxODMzOTAtNDMxYy00YTQ0LWJiYTAtZTdlZmUxM2I0YWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE4MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMzRlMmRjMDJiZjEyZmJiOTMwNzRmYTllZGM2YzFjMDM5YTg1NTVmYjIxMDFmNTJlMWM1ZWE1MDA1ODI4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8Cp1N8hfH0qWe_JX7zCdp16fiNB4BdrMDHchnHOFKs)
> > > 重新安装测试是过的
> > 
> > 截图开启debug后的页面报错
> 
> 你看看怎么个事

检查`.env`中redis密码是否正确设置

**Comment by yangjiaji1795** [comment]
> > > > @Yincmewy ![image](https://private-user-images.githubusercontent.com/73827879/357520004-bf183390-431c-4a44-bba0-e7efe13b4ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzI4MDcsIm5iZiI6MTcyMzU3MjUwNywicGF0aCI6Ii83MzgyNzg3OS8zNTc1MjAwMDQtYmYxODMzOTAtNDMxYy00YTQ0LWJiYTAtZTdlZmUxM2I0YWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE4MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMzRlMmRjMDJiZjEyZmJiOTMwNzRmYTllZGM2YzFjMDM5YTg1NTVmYjIxMDFmNTJlMWM1ZWE1MDA1ODI4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8Cp1N8hfH0qWe_JX7zCdp16fiNB4BdrMDHchnHOFKs)
> > > > 重新安装测试是过的
> > > 
> > > 
> > > 截图开启debug后的页面报错
> > 
> > 
> > 你看看怎么个事
> 
> 检查`.env`中redis密码是否正确设置

检查过了是对的

**Comment by yangjiaji1795** [comment]
> > > > > @Yincmewy ![image](https://private-user-images.githubusercontent.com/73827879/357520004-bf183390-431c-4a44-bba0-e7efe13b4ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzI4MDcsIm5iZiI6MTcyMzU3MjUwNywicGF0aCI6Ii83MzgyNzg3OS8zNTc1MjAwMDQtYmYxODMzOTAtNDMxYy00YTQ0LWJiYTAtZTdlZmUxM2I0YWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE4MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMzRlMmRjMDJiZjEyZmJiOTMwNzRmYTllZGM2YzFjMDM5YTg1NTVmYjIxMDFmNTJlMWM1ZWE1MDA1ODI4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8Cp1N8hfH0qWe_JX7zCdp16fiNB4BdrMDHchnHOFKs)
> > > > > 重新安装测试是过的
> > > > 
> > > > 
> > > > 截图开启debug后的页面报错
> > > 
> > > 
> > > 你看看怎么个事
> > 
> > 
> > 检查`.env`中redis密码是否正确设置
> 
> 检查过了是对的

找到原因了，因为我这边是使用的1panel搭建的网站，redis需要对外暴露。这个REDIS_HOST =要ip
