### ISSUE TITLE
TG被踢了还能再进吗

### ISSUE THREAD

**Issue by 1aaaaaa2** [f4team-cn/f4pan#16]
群太多了，没注意看消息

**Comment by swim233** [comment]
@1aaaaaa2 留下你的id

**Comment by 1aaaaaa2** [comment]
5789020314

**Comment by shinji0626** [comment]
我也是太多群没注意看到 @swim233 还能进群吗？id是shinji ikari

**Comment by swim233** [comment]
@shinji0626 请设置头像

**Comment by shinji0626** [comment]
@swim233 设置了下，请看看

**Comment by shinji0626** [comment]
@swim233 谢谢，进来了

**Comment by 1aaaaaa2** [comment]
> @1aaaaaa2 留下你的id

拉我一下

**Comment by fyiiisyh** [comment]
同求重新进，已经设置好头像，id是2091098154

**Comment by 1chuci** [comment]
已经设置好头像，id是5621837242

**Comment by ZTXBOSS666** [comment]
@zhantianxia6

**Comment by swim233** [comment]
> @zhantianxia6

广告Nickname 不予解封

**Comment by ENDLESS-0** [comment]
您好，我也是没来得及查看群消息被踢的，请问还可以解封进群吗？我的ID是5058281525，用户名是@t_tUmbrellA
@swim233

**Comment by WINDSHADOW456** [comment]
ID：178243497，谢谢

**Comment by swim233** [comment]
https://github.com/f4team-cn/f4pan/issues/16#issuecomment-2285201226

**Comment by swim233** [comment]
> ID：178243497，谢谢

未找到封禁记录

**Comment by WINDSHADOW456** [comment]
@swim233 怎么加群呢~~（新人不懂就问）

**Comment by WINDSHADOW456** [comment]
老哥怎么加TG群呢，刚进来确实不懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "f4team-cn/f4pan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月13日(星期二) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [f4team-cn/f4pan] TG被踢了还能再进吗 (Issue #16)





  
ID：178243497，谢谢
  
未找到封禁记录

**Comment by SebastiannWang** [comment]
你好 管理员@swim233 我今天登录发现也被t掉了，请问还能拉我进群吗？id: 518322047

**Comment by sisi0318** [comment]
不再处理 锁了
