### ISSUE TITLE
main 拉取的文件进行搭建，已成功执行 composer install
已设置运行目录，伪静态
PHP8.2
访问安装网址提示 403 Forbidden

### ISSUE THREAD

**Issue by ZZ0YY** [f4team-cn/f4pan#17]

**Comment by Yincmewy** [comment]
前端文件需要放在public文件夹下，建议从前端actions里下载

**Comment by ZZ0YY** [comment]
> 前端文件需要放在public文件夹下，建议从前端actions里下载

我将前端文件的 main 文件直接添加到后端文件的 publish 文件夹里，现在进行访问 直接提示{"code":-1,"message":"接口不存在","data":{"author":"F4Team","version":null,"installed":false,"github":"https:\/\/github.com\/f4team-cn\/f4pan","website":"https:\/\/www.f4team.cn\/"}}
![Screenshot_2024-08-12-16-26-44-28_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/user-attachments/assets/d3334c5c-c19a-4343-8e57-6b5c1304f476)

这是文件目录，我是否操作上有什么问题？我可能不太明白单独部署的步骤，感谢指教，谢谢(🙏ˊᗜˋ*)

**Comment by ZZ0YY** [comment]
> 前端文件需要放在public文件夹下，建议从前端actions里下载

我将前端的 main 文件添加到后端目录的 Publish 里文件目录如图所示![Screenshot_2024-08-12-16-45-18-34_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/user-attachments/assets/e7ee4c69-0687-4a9b-a2f2-0831df309c88)


现在访问安装网址{"code":-1,"message":"接口不存在","data":{"author":"F4Team","version":null,"installed":false,"github":"https:\/\/github.com\/f4team-cn\/f4pan","website":"https:\/\/www.f4team.cn\/"}}
出现这样的页面
我是否添加的目录不对？我对前后端分离布置不太熟练 望指教，谢谢(^🙏^)

**Comment by Yincmewy** [comment]
不是，你需要从actions下载已经编译好的版本，解压到publc目录下

**Comment by ZZ0YY** [comment]
> 不是，你需要从actions下载已经编译好的版本，解压到publc目录下

是选了最上面那个吗？里面有个 index 的压缩包
这样子还是提示刚刚的报错
现在的文件目录是这样
![Screenshot_2024-08-12-17-18-29-26_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/user-attachments/assets/09e64d72-1bc2-480a-a286-f183f86971ea)
