### ISSUE TITLE
内部500错误

### ISSUE THREAD

**Issue by Lindx999** [f4team-cn/f4pan#19]
![PixPin_2024-08-13_13-14-34](https://github.com/user-attachments/assets/f24a4a6a-8bc2-4c20-a5d4-9c5413d80d68)
![微信图片_20240813131547](https://github.com/user-attachments/assets/9f8ed478-3d22-4701-98a0-0fec58e45313)
![PixPin_2024-08-13_13-13-43](https://github.com/user-attachments/assets/2c6454b7-0848-45b1-b239-973a874bc4eb)
我的环境都符合，为啥还是有内部报错呢！

用的是Nginx伪静态（前端+后端）:
![PixPin_2024-08-13_13-18-51](https://github.com/user-attachments/assets/2dac0167-b9fa-4ed1-b0ae-c042fb830caf)

**Comment by Yincmewy** [comment]
可能是cookie过长，尝试缩减到只留下`BDUSS`和`STOKEN`
如果还不行请在网站根目录**新建**一个`.env`文件写入APP_DEBUG=true打开f12抓报错的网络请求，截图响应体发送过来

**Comment by Lindx999** [comment]
> 可能是cookie过长，尝试缩减到只留下`BDUSS`和`STOKEN` 如果还不行请在网站根目录**新建**一个`.env`文件写入APP_DEBUG=true打开f12抓报错的网络请求，截图响应体发送过来

试过了，还是不行！当开始打开安装页面的时候就提示500了

**Comment by Yincmewy** [comment]
> > 可能是cookie过长，尝试缩减到只留下`BDUSS`和`STOKEN` 如果还不行请在网站根目录**新建**一个`.env`文件写入APP_DEBUG=true打开f12抓报错的网络请求，截图响应体发送过来
> 
> 试过了，还是不行！当开始打开安装页面的时候就提示500了

**清空**你的数据库，建议删除重建

**Comment by Lindx999** [comment]
> > > 可能是cookie过长，尝试缩减到只留下`BDUSS`和`STOKEN` 如果还不行请在网站根目录**新建**一个`.env`文件写入APP_DEBUG=true打开f12抓报错的网络请求，截图响应体发送过来
> > 
> > 
> > 试过了，还是不行！当开始打开安装页面的时候就提示500了
> 
> **清空**你的数据库，建议删除重建

 还是不行，能帮我看看网站配置文件有没有问题，**composer install** 是没有报错的！

**Comment by Yingyya** [comment]
刚开始提示500是正常的。记得解决一下@Yincmewy

**Comment by Lindx999** [comment]
![image](https://github.com/user-attachments/assets/dc5134e1-7636-40d5-a216-def01f55b596)
提示的还是环境问题，

**Comment by Yincmewy** [comment]
install接口错误，抓包看一下返回

**Comment by Lindx999** [comment]
> install接口错误，抓包看一下返回

![image](https://github.com/user-attachments/assets/37182044-02c4-4414-8d61-37602571ee37)
![image](https://github.com/user-attachments/assets/107bfc29-220e-428f-b895-6862719c74e8)
这样的

**Comment by Yincmewy** [comment]
> > install接口错误，抓包看一下返回
> 
> ![image](https://github.com/user-attachments/assets/37182044-02c4-4414-8d61-37602571ee37)
> ![image](https://github.com/user-attachments/assets/107bfc29-220e-428f-b895-6862719c74e8)
> 这样的


请在网站根目录新建一个.env文件写入APP_DEBUG=true打开f12抓报错的网络请求，截图响应体发送过来

**Comment by Lindx999** [comment]
> > > install接口错误，抓包看一下返回
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/14357778/357308543-37182044-02c4-4414-8d61-37602571ee37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzQ3NDAsIm5iZiI6MTcyMzUzNDQ0MCwicGF0aCI6Ii8xNDM1Nzc3OC8zNTczMDg1NDMtMzcxODIwNDQtMDJjNC00NDE0LThkNjEtMzc2MDI1NzFlZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA3MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzNkMDhkNWNmNjg1ZGEzZDNhMjAzOWRlMDBjNjJhMTFkMzU2MjExYjU1OWExYmY1YzkzN2FlNzA4ZmYwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4pJG6ImYpfdB2SrXc1tfaBkshCVKpBKaJaTlC58EdI)
> > ![image](https://private-user-images.githubusercontent.com/14357778/357308986-107bfc29-220e-428f-b895-6862719c74e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzQ3NDAsIm5iZiI6MTcyMzUzNDQ0MCwicGF0aCI6Ii8xNDM1Nzc3OC8zNTczMDg5ODYtMTA3YmZjMjktMjIwZS00MjhmLWI4OTUtNjg2MjcxOWM3NGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA3MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjY2I2NmM3NmUzNzgwYzkzNjEzYzBkYzVmMDVkYjM1YmY5Y2FkZThmNGM1ZjI1NWNhN2NmMTQ0ZDAzNDRkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jfwS2uzbw7AK53MEkcs9PaPZ-K1UQsWK_7ASjzXBbc)
> > 这样的
> 
> 请在网站根目录新建一个`.env`文件写入`APP_DEBUG=true`打开f12抓报错的网络请求，截图响应体发送过来

![image](https://github.com/user-attachments/assets/573cfc3c-52c2-4493-8398-1d9988e27161)

**Comment by Yincmewy** [comment]
> > > > install接口错误，抓包看一下返回
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/14357778/357308543-37182044-02c4-4414-8d61-37602571ee37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzQ3NDAsIm5iZiI6MTcyMzUzNDQ0MCwicGF0aCI6Ii8xNDM1Nzc3OC8zNTczMDg1NDMtMzcxODIwNDQtMDJjNC00NDE0LThkNjEtMzc2MDI1NzFlZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA3MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzNkMDhkNWNmNjg1ZGEzZDNhMjAzOWRlMDBjNjJhMTFkMzU2MjExYjU1OWExYmY1YzkzN2FlNzA4ZmYwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4pJG6ImYpfdB2SrXc1tfaBkshCVKpBKaJaTlC58EdI)
> > > ![image](https://private-user-images.githubusercontent.com/14357778/357308986-107bfc29-220e-428f-b895-6862719c74e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzQ3NDAsIm5iZiI6MTcyMzUzNDQ0MCwicGF0aCI6Ii8xNDM1Nzc3OC8zNTczMDg5ODYtMTA3YmZjMjktMjIwZS00MjhmLWI4OTUtNjg2MjcxOWM3NGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA3MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjY2I2NmM3NmUzNzgwYzkzNjEzYzBkYzVmMDVkYjM1YmY5Y2FkZThmNGM1ZjI1NWNhN2NmMTQ0ZDAzNDRkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jfwS2uzbw7AK53MEkcs9PaPZ-K1UQsWK_7ASjzXBbc)
> > > 这样的
> > 
> > 请在网站根目录新建一个`.env`文件写入`APP_DEBUG=true`打开f12抓报错的网络请求，截图响应体发送过来
> 
> ![image](https://github.com/user-attachments/assets/573cfc3c-52c2-4493-8398-1d9988e27161)
> 这个  .evn 放在了public 的上一层目录

没有正确开启，请检查是否设置成功

**Comment by Lindx999** [comment]
![image](https://github.com/user-attachments/assets/5608a14c-e1f9-4dd4-ad58-cf689e5e33d2)

**Comment by Lindx999** [comment]
> > > > > install接口错误，抓包看一下返回
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/14357778/357308543-37182044-02c4-4414-8d61-37602571ee37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzQ3NDAsIm5iZiI6MTcyMzUzNDQ0MCwicGF0aCI6Ii8xNDM1Nzc3OC8zNTczMDg1NDMtMzcxODIwNDQtMDJjNC00NDE0LThkNjEtMzc2MDI1NzFlZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA3MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzNkMDhkNWNmNjg1ZGEzZDNhMjAzOWRlMDBjNjJhMTFkMzU2MjExYjU1OWExYmY1YzkzN2FlNzA4ZmYwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4pJG6ImYpfdB2SrXc1tfaBkshCVKpBKaJaTlC58EdI)
> > > > ![image](https://private-user-images.githubusercontent.com/14357778/357308986-107bfc29-220e-428f-b895-6862719c74e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzQ3NDAsIm5iZiI6MTcyMzUzNDQ0MCwicGF0aCI6Ii8xNDM1Nzc3OC8zNTczMDg5ODYtMTA3YmZjMjktMjIwZS00MjhmLWI4OTUtNjg2MjcxOWM3NGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA3MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjY2I2NmM3NmUzNzgwYzkzNjEzYzBkYzVmMDVkYjM1YmY5Y2FkZThmNGM1ZjI1NWNhN2NmMTQ0ZDAzNDRkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jfwS2uzbw7AK53MEkcs9PaPZ-K1UQsWK_7ASjzXBbc)
> > > > 这样的
> > > 
> > > 
> > > 请在网站根目录新建一个`.env`文件写入`APP_DEBUG=true`打开f12抓报错的网络请求，截图响应体发送过来
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/14357778/357317040-573cfc3c-52c2-4493-8398-1d9988e27161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzc0MDIsIm5iZiI6MTcyMzUzNzEwMiwicGF0aCI6Ii8xNDM1Nzc3OC8zNTczMTcwNDAtNTczY2ZjM2MtNTJjMi00NDkzLTgzOTgtMWQ5OTg4ZTI3MTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4MTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZGI4MGI3OWZjOTU0NGUxMzliZWY1YjdjM2E1M2JkZWYyNzVlNWNmNWVlYWU4OTYyY2Q2ZTkxNzcxZjI1MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3hd1qMgx6E2SCz0P4huMQMVk6lEAnWaMx3CxIkEV5fw)
> > 这个  .evn 放在了public 的上一层目录
> 
> 没有正确开启，请检查是否设置成功

这样的

**Comment by Lindx999** [comment]
问题已经解决。麻烦大佬了！
 * 我的问题是 www-data 权限和 MySQL 问题
 * www-data 问题是把文件夹的用户和用户组改到www-data
  ``` chown www-data:www-data /var/www -R
```
 
各位大佬见笑了！
