### ISSUE TITLE
可以出个详细点的搭建教程吗

### ISSUE THREAD

**Issue by czbbhack** [f4team-cn/f4pan#21]
试着搭建出解析页面  ，动态解析密码页面就搞不明白了 T T

**Comment by Yingyya** [comment]
动态密码指需要使用额外接口生成一个密码来使用。

**Comment by Yincmewy** [comment]
动态密钥获取方法:

登录后台，进入apikey管理页面，新增一个apikey
GET访问`/api/public/get_parse_key?apikey={apikey}`获取动态解析密钥
把`{apikey}`替换成后台生成的apikey
