### ISSUE TITLE
开始下载页面-相关报错信息

### ISSUE THREAD

**Issue by Wangxiaolong-ME** [f4team-cn/f4pan#23]
### **报错信息**
![image](https://github.com/user-attachments/assets/03424c0e-ea5e-43e1-bdcb-d7621f3a0952)
![image](https://github.com/user-attachments/assets/187dbfd6-2b2e-4983-8318-f80e4711485c)
提示：获取svip失败, 请重试

### 这里有一点疑问，这个项目原理是通过实际的网盘超级会员账号请求官方接口去解析吗，如果这样的话添加普通账户是不可行的是吧
![image](https://github.com/user-attachments/assets/19dc708c-b8cd-45c7-b165-aa16d07b3cbb)

### **这里还想确认一点，系统配置页的cookie就是设置账号管理页添加的账户的Cookie吧**
![image](https://github.com/user-attachments/assets/7e7bead0-b021-44ed-9c38-609ed1d199e9)

**Comment by Yincmewy** [comment]
因为普通账号解析出的文件无法使用多线程下载，且下载速度极低，因此目前没有普通账号的解析逻辑

系统配置页的cookie是用来获取文件列表的，因此是否是svip不影响此功能

账号管理页面的账号是需要svip的

**Comment by dashouzhang** [comment]
我算是理解了，就是用普通账户的cookie获取要下载的文件列表，然后把获取的文件列表用svip账户解析出来加速链接，进行不同下载方式进行下载。但是为什么链接要压缩包形式进行下载，是为了一次可以生成多个文件的解析链接吗？但是单文件下载的体验会因为压缩包的生成下降不少。能否考虑直接显示连接。
