### ISSUE TITLE
环境都正常，但是安装失败

### ISSUE THREAD

**Issue by huangbh1024** [f4team-cn/f4pan#24]
![image](https://github.com/user-attachments/assets/a67693d6-a404-4a6b-8f65-fa63d3416bfa)

**Comment by Yincmewy** [comment]
见[#9](https://github.com/f4team-cn/f4pan/issues/9#issuecomment-2282758961)

**Comment by huangbh1024** [comment]
> 见[#9](https://github.com/f4team-cn/f4pan/issues/9#issuecomment-2282758961)

![image](https://github.com/user-attachments/assets/467e981d-8aa1-40be-8f0a-fc134ff7122c)
![image](https://github.com/user-attachments/assets/399bbcec-3de1-421d-afe2-4b932eb1395f)

**Comment by Yincmewy** [comment]
> 
> 
> 
> 
> > 见[#9](https://github.com/f4team-cn/f4pan/issues/9#issuecomment-2282758961)
> 
> ![image](https://github.com/user-attachments/assets/467e981d-8aa1-40be-8f0a-fc134ff7122c)
> ![image](https://github.com/user-attachments/assets/399bbcec-3de1-421d-afe2-4b932eb1395f)
> 

**清空**你的数据库后重试

**Comment by huangbh1024** [comment]
看了一下，报错信息应该是这个

> > > 见[#9](https://github.com/f4team-cn/f4pan/issues/9#issuecomment-2282758961)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/72372968/358211836-467e981d-8aa1-40be-8f0a-fc134ff7122c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjM4NjUsIm5iZiI6MTcyMzcyMzU2NSwicGF0aCI6Ii83MjM3Mjk2OC8zNTgyMTE4MzYtNDY3ZTk4MWQtOGFhMS00MGJlLThmMGEtZmMxMzRmZjcxMjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyMDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNGZhOGQ0NDkwOGQ4ODdkZThjZGEyZTE2ZjA5YzRjMzYzMDI1YjkxOWM1NDMxNWQ1ZDJlMmJiODE3ZDIxMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yOCGw5q-z37tw0Tj1oyssr1r6BNNkumtCUPqobwoIng)
> > ![image](https://private-user-images.githubusercontent.com/72372968/358211894-399bbcec-3de1-421d-afe2-4b932eb1395f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjM4NjUsIm5iZiI6MTcyMzcyMzU2NSwicGF0aCI6Ii83MjM3Mjk2OC8zNTgyMTE4OTQtMzk5YmJjZWMtM2RlMS00MjFkLWFmZTItNGI5MzJlYjEzOTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyMDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NzU5YTFhMTc0ZjJhNTRjN2EwMmFiNzIwY2NkZWQyYjU5OTI2ZjAyMmI0NmRjMTg0ZTUzZGY1MTY4NTMzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ld849AX-kzs6x9F9wFt9s6ejLlSeLFHgicl8Wx5XXII)
> 
> **清空**你的数据库后重试

看报错看出来了，刚刚删掉数据库重新安装，正常了，麻烦了
