### ISSUE TITLE
链接解析成功了，但是解析出来的link，直接使用浏览器打开，没有效果

### ISSUE THREAD

**Issue by huangbh1024** [f4team-cn/f4pan#26]
![image](https://github.com/user-attachments/assets/3654b7c1-b85c-4f35-a718-1070f76e2d5b)
![image](https://github.com/user-attachments/assets/7b62a9e7-890f-49c6-abff-65d422fde305)

**Comment by Yincmewy** [comment]
使用idm设置ua下载，或使用motrix推送下载
