### ISSUE TITLE
使用最新发行版搭建成功后，进入后台仍出现500错误

### ISSUE THREAD

**Issue by ZZ0YY** [f4team-cn/f4pan#27]
这是开了Debug
![Screenshot_2024-08-16-14-23-48-71_2279741c0dede0d4ce8cbad47dbe178c.jpg](https://github.com/user-attachments/assets/e6b88737-45c4-4f34-be92-39d9d040e32b)

**Comment by Yingyya** [comment]
执行 `composer install` 重新下载依赖。

**Comment by ZZ0YY** [comment]
> 执行 `composer install` 重新下载依赖。

Nothing to install, update or remove
Generating autoload files
> @php think service:discover
Succeed!
> @php think vendor:publish
File /www/wwwroot/pan1/tp8.0/config/trace.php exist!
Succeed!
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!


理论上这个最终输出没有问题，但是依然是上面的报错

![Screenshot_2024-08-17-10-19-54-45.jpg](https://github.com/user-attachments/assets/ae0d832a-71d6-4c17-960d-a8fc02090358)

这是运行文件，虽然标黄有点多 
但是
最后有提示 "Nothing to install, update or remove"，表示所有依赖项已经正确安装或是已经是最新版本。
生成了自动加载文件：Generating autoload files。
ThinkPHP 命令 @php think service:discover 和 @php think vendor:publish 成功执行，并显示 "Succeed!"。
没有报错，只是一些关于 PHP 8 的弃用通知（Deprecation Notice），这些并不会影响安装结果。
所以可以确定 composer install 命令执行成功。

**Comment by ZZ0YY** [comment]
就是说现在属于是能够获取分享链接文件的列表
但是后台进不去

**Comment by Yingyya** [comment]
给 `vendor` 文件夹的所有者设置为宝塔用户

**Comment by ZZ0YY** [comment]
> 给 `vendor` 文件夹的所有者设置为宝塔用户

已尝试 没有区别 使用了 root 用户和 www 用户也没有区别
是有什么限制吗？一个服务器不能搭建两个？
我第一个网站搭建成功了 使用PHP8.0，目前也还在使用 但是是旧版
现在这个是第二个，使用PhP8.2，该装的扩展也全都装上了

**Comment by ZZ0YY** [comment]
> 给 `vendor` 文件夹的所有者设置为宝塔用户

使用全新的系统重新一步步进行安装 依然是这样
请问会不会整合包有一定的问题
使用PHP8.2

**Comment by ZZ0YY** [comment]
> 给 `vendor` 文件夹的所有者设置为宝塔用户

vendor 文件夹少了 lcobucci 文件夹，依赖没有安装上，
执行composer fund 出现：![IMG_20240820_101514_663.jpg](https://github.com/user-attachments/assets/f23f6eb7-d591-419f-989c-c6d46441c265)

不知什么原因
这是完整一点的：![Screenshot_2024-08-19-23-13-27-45.jpg](https://github.com/user-attachments/assets/3cece1f8-0296-4027-847b-cb39ed7a02fb)

执行 composer require lcobucci/jwt
出现：![Screenshot_2024-08-19-23-27-34-25_3d419158bad5872c40592a6c9956e692.jpg](https://github.com/user-attachments/assets/f4888dcd-54f9-4db4-996d-43e33bea769f)

然后再执行 composer update 是无穷的等待

**Comment by Yincmewy** [comment]
依赖未正确安装，请尝试单独安装所需依赖
