### ISSUE TITLE
大佬，可以帮我看看这是什么问题吗？

### ISSUE THREAD

**Issue by caoyongit** [f4team-cn/f4pan#28]
这个是账号挂了吗？
![SCR-20240816-rtub](https://github.com/user-attachments/assets/c20465c3-28aa-4b3e-b3af-0d0df23008d1)

**Comment by Yincmewy** [comment]
ua，改成`netdisk;`注意英文分号

**Comment by caoyongit** [comment]
感谢回复如此迅速，ua指的应该是下图的参数吧？改了之后还是一样的错误，特地还重新安装了一下，清空了网站和数据库。
![SCR-20240816-sxnf](https://github.com/user-attachments/assets/a2a1063a-a885-4dc8-9bcb-e29df8f46174)
这个是请求参数，返回的报错信息如上条评论的还是一样
<img width="376" alt="SCR-20240816-taxq" src="https://github.com/user-attachments/assets/85189d52-aa06-4167-9cf2-14e362fc4140">

**Comment by Yincmewy** [comment]
> 感谢回复如此迅速，ua指的应该是下图的参数吧？改了之后还是一样的错误，特地还重新安装了一下，清空了网站和数据库。
> ![SCR-20240816-sxnf](https://github.com/user-attachments/assets/a2a1063a-a885-4dc8-9bcb-e29df8f46174)
> 这个是请求参数，返回的报错信息如上条评论的还是一样
> <img width="376" alt="SCR-20240816-taxq" src="https://github.com/user-attachments/assets/85189d52-aa06-4167-9cf2-14e362fc4140">
> 
> 

换个账号或者服务器重试，api返回了空值

**Comment by caoyongit** [comment]
> > 感谢回复如此迅速，ua指的应该是下图的参数吧？改了之后还是一样的错误，特地还重新安装了一下，清空了网站和数据库。
> > ![SCR-20240816-sxnf](https://private-user-images.githubusercontent.com/7878291/358606705-a2a1063a-a885-4dc8-9bcb-e29df8f46174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTc1MTEsIm5iZiI6MTcyMzgxNzIxMSwicGF0aCI6Ii83ODc4MjkxLzM1ODYwNjcwNS1hMmExMDYzYS1hODg1LTRkYzgtOWJjYi1lMjlkZjhmNDYxNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTQwNjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjY3ZmQ3ODFmYjhjZWIxYTE4OGVkMzllMDY0MDMzYmMyMTQ0MjlhNmYwMWRjNTRhZWQyYjNkN2UyNzczNTBjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tHPewq1Qx4rmIeq7zDRH_wLNHRaGasx4_EZu5mx9Woo)
> > 这个是请求参数，返回的报错信息如上条评论的还是一样
> > <img alt="SCR-20240816-taxq" width="376" src="https://private-user-images.githubusercontent.com/7878291/358608017-85189d52-aa06-4167-9cf2-14e362fc4140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTc1MTEsIm5iZiI6MTcyMzgxNzIxMSwicGF0aCI6Ii83ODc4MjkxLzM1ODYwODAxNy04NTE4OWQ1Mi1hYTA2LTQxNjctOWNmMi0xNGUzNjJmYzQxNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTQwNjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRjYzY4MzQzNmY0NDJlNzgyZjZjNTAwZjc3YmFjMjEyNGRiZTY3N2UzYjgzNGY4OWJjZGQzMjZkY2QxNDJkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ppYbIrc6yUFDglcIPNiAzsuodsSY7YVz5daa7W5wbGY">
> 
> 换个账号或者服务器重试，api返回了空值

感谢大佬，我再试一试
