### ISSUE TITLE
接口一直不存在为什么

### ISSUE THREAD

**Issue by huangwei-yan** [f4team-cn/f4pan#29]
![1723816688386](https://github.com/user-attachments/assets/1d6c3779-3dd4-43b0-a914-d08e0e584a13)

**Comment by Yincmewy** [comment]
伪静态

**Comment by huangwei-yan** [comment]
> 伪静态

![Uploading 1723872123953.png…]()
那这个那

**Comment by huangwei-yan** [comment]
> 伪静态

![1723876684391](https://github.com/user-attachments/assets/8ce727a7-116a-4750-a26d-2d1d0c067b1b)
这是阿帕奇配置了伪静态

**Comment by Yincmewy** [comment]
> > 伪静态
> 
> nginx配置了伪静态 我把根目录换成public 报500  换成根目录 就报403
> 

报错什么

**Comment by huangwei-yan** [comment]
> > > 伪静态
> > 
> > 
> > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> 


> > > 伪静态
> > 
> > 
> > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> 
> 报错什么

500 Internal Server Error
nginx/1.16.1

**Comment by Yincmewy** [comment]
> > > > 伪静态
> > > 
> > > 
> > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > 
> 
> 
> > > > 伪静态
> > > 
> > > 
> > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > 
> > 报错什么
> 
> 500 Internal Server Error
> nginx/1.16.1
> 

nginx配置readme的`前端+后端`伪静态
下载发行版的完整包
跟随readme的步骤进行安装

**Comment by huangwei-yan** [comment]
> > > > > 伪静态
> > > > 
> > > > 
> > > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > 
> > 
> > > > > 伪静态
> > > > 
> > > > 
> > > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > > 
> > > 
> > > 报错什么
> > 
> > 
> > 500 内部服务器错误
> > nginx/1.16.1
> 
> nginx 配置自述文件的`前端+后端`伪静态 下载发行版的完整包， 然后自述文件的步骤进行安装

这不是前后分离的嘛，完整版在那个地方

**Comment by Yincmewy** [comment]
> > > > > > 伪静态
> > > > > 
> > > > > 
> > > > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > > 
> > > 
> > > > > > 伪静态
> > > > > 
> > > > > 
> > > > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > > > 
> > > > 
> > > > 报错什么
> > > 
> > > 
> > > 500 内部服务器错误
> > > nginx/1.16.1
> > 
> > nginx 配置自述文件的`前端+后端`伪静态 下载发行版的完整包， 然后自述文件的步骤进行安装
> 
> 这不是前后分离的嘛，完整版在那个地方

complete那个

**Comment by huangwei-yan** [comment]
> > > > > > > 伪静态
> > > > > > 
> > > > > > 
> > > > > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > > > 
> > > > 
> > > > > > > 伪静态
> > > > > > 
> > > > > > 
> > > > > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > > > > 
> > > > > 
> > > > > 报错什么
> > > > 
> > > > 
> > > > 500 内部服务器错误
> > > > nginx/1.16.1
> > > 
> > > 
> > > nginx 配置自述文件的`前端+后端`伪静态 下载发行版的完整包， 然后自述文件的步骤进行安装
> > 
> > 
> > 这不是前后分离的嘛，完整版在那个地方
> 
> complete那个

为什么一直获取svip失败，我用的是vip的cookie呀

**Comment by Yincmewy** [comment]
> > > > > > > > 伪静态
> > > > > > > 
> > > > > > > 
> > > > > > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > > > > 
> > > > > 
> > > > > > > > 伪静态
> > > > > > > 
> > > > > > > 
> > > > > > > nginx 配置了伪静态 我把根目录换成public 报500 换成根目录就报403
> > > > > > 
> > > > > > 
> > > > > > 报错什么
> > > > > 
> > > > > 
> > > > > 500 内部服务器错误
> > > > > nginx/1.16.1
> > > > 
> > > > 
> > > > nginx 配置自述文件的`前端+后端`伪静态 下载发行版的完整包， 然后自述文件的步骤进行安装
> > > 
> > > 
> > > 这不是前后分离的嘛，完整版在那个地方
> > 
> > complete那个
> 
> 为什么一直获取svip失败，我用的是vip的cookie呀

需要svip，如果还是提示获取svip失败就是账号被限制了
