### ISSUE TITLE
这是什么问题呢，没排查出来

### ISSUE THREAD

**Issue by xia-66** [f4team-cn/f4pan#30]
![1723897231534](https://github.com/user-attachments/assets/2a09d34a-aefd-4e00-bca1-2931afc3ef86)
![1723897280039](https://github.com/user-attachments/assets/863fe0c7-2561-4d20-a490-f9f057dc1dde)

**Comment by Yincmewy** [comment]
> ![1723897231534](https://github.com/user-attachments/assets/2a09d34a-aefd-4e00-bca1-2931afc3ef86)
> ![1723897231534](https://github.com/user-attachments/assets/4347d49b-3324-4f0a-9ed3-3c630e05a23c)
> 

开debug截图响应体

**Comment by xia-66** [comment]
> > ![1723897231534](https://private-user-images.githubusercontent.com/108531300/358844919-2a09d34a-aefd-4e00-bca1-2931afc3ef86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTc4NTMsIm5iZiI6MTcyMzg5NzU1MywicGF0aCI6Ii8xMDg1MzEzMDAvMzU4ODQ0OTE5LTJhMDlkMzRhLWFlZmQtNGUwMC1iY2ExLTI5MzFhZmMzZWY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMjI1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDljNGY2MGIyY2FjODdiNGNkN2EzNDUyOTgyYzBjOTMyNjBiOGZhZDMxYjYzNDQyYWE2MDQ2N2Q5ODMxOWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3EYHPvq3hJ86YLbUOvVTGOYurQDBf6MERmQurzluQFY)
> > ![1723897231534](https://private-user-images.githubusercontent.com/108531300/358844929-4347d49b-3324-4f0a-9ed3-3c630e05a23c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTc4NTMsIm5iZiI6MTcyMzg5NzU1MywicGF0aCI6Ii8xMDg1MzEzMDAvMzU4ODQ0OTI5LTQzNDdkNDliLTMzMjQtNGYwYS05ZWQzLTNjNjMwZTA1YTIzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMjI1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTNjMzI3ZWJjNDJhNGM1YmJiNWEzMGE3NTRjNTI4NTE2Y2EyOGJjYWI2MDVmYmJiNzlkZDMxN2FiZDc5OWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.15NPLdp1Odg3kJ55XM5y83x1uBiuGVbRb6OjM9SN5cI)
> 
> 开debug截图响应体

开debug后又正常了，我最开始能用，过了半天就这个问题，        $fs_id 
        $randsk 
        $share_id 
        $uk 
        $surl 都能拿到，就是解析$realLink出现问题的

**Comment by xia-66** [comment]
...
