### ISSUE TITLE
有没有人遇到aria2 下载遇到的问题

### ISSUE THREAD

**Issue by Annmoy** [f4team-cn/f4pan#32]
## 下载的时候一直报错，web下载是没有问题的
![PixPin_2024-08-19_09-00-04](https://github.com/user-attachments/assets/1f996475-536b-41fa-941b-9e297cb1bccc)
![image](https://github.com/user-attachments/assets/6f290cfc-b317-4ed5-a01e-9a31554f39b6)

**Comment by dushu8** [comment]
你是自己部署的吧
你可以在 \app\controller\Parse.php 文件的170行左右 添加   'filefsid' => (int)$fs_id,

**Comment by Annmoy** [comment]
> 你是自己部署的吧 你可以在 \app\controller\Parse.php 文件的170行左右 添加 'filefsid' => (int)$fs_id,

谢谢大佬，解决了！是自己部署的！
