### ISSUE TITLE
点击开始下载的问题。

### ISSUE THREAD

**Issue by liaoke01** [f4team-cn/f4pan#33]
用windows宝塔面板部署环境什么的已经安装好了，但是点击开始下载就报内部服务器500错误。
![屏幕截图 2024-08-19 150157](https://github.com/user-attachments/assets/f57ae6fa-fd3d-46b7-8ce3-fba0936c6b03)

**Comment by liaoke01** [comment]
![屏幕截图 2024-08-19 150513](https://github.com/user-attachments/assets/6421a904-6fff-4d7a-9e0d-57c6cdeb9f2f)
打开错误详情日志是这个。

**Comment by Yincmewy** [comment]
> ![屏幕截图 2024-08-19 150513](https://github.com/user-attachments/assets/6421a904-6fff-4d7a-9e0d-57c6cdeb9f2f)
> 打开错误详情日志是这个。

无法解析，设置的解析账号内分享的文件
