### ISSUE TITLE
获取svip失败, 请重试

### ISSUE THREAD

**Issue by wawuo** [f4team-cn/f4pan#34]
需要svip吗？

**Comment by wawuo** [comment]
点击开始下载时提示：获取svip失败, 请重试

**Comment by Wangxiaolong-ME** [comment]
https://github.com/f4team-cn/f4pan/issues/23
可以参考这个回答

**Comment by Yincmewy** [comment]
> > #23 可以参考这个回答
> 
>   好的，谢谢。我看了那个回issue,试总结一下就是：要在账号里设置一个svip账号。才能正解解析,是这样吗?

是这样的
