### ISSUE TITLE
环境检查失败

### ISSUE THREAD

**Issue by suiyuanccccc** [f4team-cn/f4pan#37]
![image](https://github.com/user-attachments/assets/8b72ea25-0c57-469d-9bae-e9b2a71325f9)
![image](https://github.com/user-attachments/assets/c29bbcf3-6003-4ec4-a545-db136d9247f2)
宝塔两个函数已关闭，拓展已经安装，但是卡环境检查
![image](https://github.com/user-attachments/assets/b49f5ee1-9aa8-4dc4-ad51-e1698a58ff3d)
以上是check_env返回值，缺少../vendor/autoload.php
![image](https://github.com/user-attachments/assets/f7c03894-b98a-4f76-9a9d-6b243a494b26)

**Comment by Yincmewy** [comment]
在网站目录执行`composer install`
