### ISSUE TITLE
报错10501:SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by suiyuanccccc** [f4team-cn/f4pan#42]
已经安装完毕，本次为第一次解析直链，后台账号密码已设置，MySQL账密正确
完整报错码，敏感信息已经用"码"覆盖
{
    "code": 10501,
    "message": "SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)",
    "traces": [
        {
            "name": "think\\db\\exception\\PDOException",
            "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/PDOConnection.php",
            "line": 836,
            "code": 10501,
            "message": "SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)",
            "trace": [
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/connector\/Mysql.php",
                    "line": 68,
                    "function": "getPDOStatement",
                    "class": "think\\db\\PDOConnection",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/PDOConnection.php",
                    "line": 438,
                    "function": "getFields",
                    "class": "think\\db\\connector\\Mysql",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/PDOConnection.php",
                    "line": 395,
                    "function": "getTableFieldsInfo",
                    "class": "think\\db\\PDOConnection",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/PDOConnection.php",
                    "line": 360,
                    "function": "getCachedSchemaInfo",
                    "class": "think\\db\\PDOConnection",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/PDOConnection.php",
                    "line": 424,
                    "function": "getSchemaInfo",
                    "class": "think\\db\\PDOConnection",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/PDOConnection.php",
                    "line": 513,
                    "function": "getTableInfo",
                    "class": "think\\db\\PDOConnection",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/concern\/TableFieldInfo.php",
                    "line": 60,
                    "function": "getFieldsType",
                    "class": "think\\db\\PDOConnection",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/db\/concern\/TableFieldInfo.php",
                    "line": 72,
                    "function": "getFieldsType",
                    "class": "think\\db\\Query",
                    "type": "->"
                },
                {
                    "function": "getFieldType",
                    "class": "think\\db\\Query",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/Model.php",
                    "line": 1150,
                    "function": "call_user_func_array"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/model\/concern\/TimeStamp.php",
                    "line": 82,
                    "function": "__call",
                    "class": "think\\Model",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/model\/concern\/TimeStamp.php",
                    "line": 62,
                    "function": "checkTimeFieldType",
                    "class": "think\\Model",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/service\/ModelService.php",
                    "line": 35,
                    "function": "isAutoWriteTimestamp",
                    "class": "think\\Model",
                    "type": "->"
                },
                {
                    "function": "think\\service\\{closure}",
                    "class": "think\\service\\ModelService",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-orm\/src\/Model.php",
                    "line": 267,
                    "function": "call_user_func"
                },
                {
                    "file": "\/www\/wwwroot\/php\/app\/middleware\/VisitRecorder.php",
                    "line": 13,
                    "function": "__construct",
                    "class": "think\\Model",
                    "type": "->"
                },
                {
                    "function": "handle",
                    "class": "app\\middleware\\VisitRecorder",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Middleware.php",
                    "line": 134,
                    "function": "call_user_func"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 66,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Route.php",
                    "line": 756,
                    "function": "then",
                    "class": "think\\Pipeline",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Http.php",
                    "line": 208,
                    "function": "dispatch",
                    "class": "think\\Route",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Http.php",
                    "line": 198,
                    "function": "dispatchToRoute",
                    "class": "think\\Http",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 59,
                    "function": "think\\{closure}",
                    "class": "think\\Http",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/middleware\/AllowCrossDomain.php",
                    "line": 61,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->"
                },
                {
                    "function": "handle",
                    "class": "think\\middleware\\AllowCrossDomain",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Middleware.php",
                    "line": 134,
                    "function": "call_user_func"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/think-trace\/src\/TraceDebug.php",
                    "line": 71,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->"
                },
                {
                    "function": "handle",
                    "class": "think\\trace\\TraceDebug",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Middleware.php",
                    "line": 134,
                    "function": "call_user_func"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 66,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Http.php",
                    "line": 199,
                    "function": "then",
                    "class": "think\\Pipeline",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/vendor\/topthink\/framework\/src\/think\/Http.php",
                    "line": 162,
                    "function": "runWithRequest",
                    "class": "think\\Http",
                    "type": "->"
                },
                {
                    "file": "\/www\/wwwroot\/php\/public\/index.php",
                    "line": 20,
                    "function": "run",
                    "class": "think\\Http",
                    "type": "->"
                }
            ],
            "source": {
                "first": 827,
                "source": [
                    "            } else {\n",
                    "                if ($this->reConnectTimes < 4 && $this->isBreak($e)) {\n",
                    "                    $this->reConnectTimes++;\n",
                    "\n",
                    "                    return $this->close()->getPDOStatement($sql, $bind, $master, $procedure);\n",
                    "                }\n",
                    "            }\n",
                    "\n",
                    "            if ($e instanceof \\PDOException) {\n",
                    "                throw new PDOException($e, $this->config, $this->getLastsql());\n",
                    "            } else {\n",
                    "                throw $e;\n",
                    "            }\n",
                    "        }\n",
                    "    }\n",
                    "\n",
                    "    \/**\n",
                    "     * 执行语句.\n",
                    "     *\n"
                ]
            }
        }
    ],
    "datas": {
        "PDO Error Info": {
            "SQLSTATE": "HY000",
            "Driver Error Code": 1045,
            "Driver Error Message": "Access denied for user 'root'@'localhost' (using password: NO)"
        },
        "Database Status": {
            "Error Code": 10501,
            "Error Message": "SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)",
            "Error SQL": ""
        },
        "Database Config": {
            "type": "mysql",
            "hostname": "127.0.0.1",
            "database": "",
            "hostport": "3306",
            "dsn": "",
            "params": [],
            "charset": "utf8",
            "prefix": "",
            "deploy": 0,
            "rw_separate": false,
            "master_num": 1,
            "slave_no": "",
            "read_master": false,
            "fields_strict": true,
            "fields_cache": false,
            "trigger_sql": true,
            "builder": "",
            "query": "",
            "break_reconnect": false,
            "break_match_str": [],
            "auto_param_bind": true
        }
    },
    "tables": {
        "GET Data": [],
        "POST Data": [],
        "Files": null,
        "Cookies": {
            "thinkphp_show_page_trace": "0|0",
            "locale": "zh-cn",
            "36709c1213f7b62904bd0449e5cc9532_ssl": "affd58f5-b999-49cb-a65f-61d36980e8b4.RkLmboEUK5jAnYBRzN6N5svkdHI",
            "7b423f28fb9dbb33431ad251ec8408cc_ssl": "f5c37888-ba61-4508-9b9c-a37d4d36b70e.ZNIXCttMX9XIskUhngaLB13MJeo",
            "87262c95b25deb0d9458185d23efc85d_ssl": "0e770092-2b9e-4ba3-a6e4-84c6dc46c097.jKb2dJ_NUD_5eWqzw0NKsAMCHAg",
            "7cf654c96b4a588b0e334821bb5943c6_ssl": "849ef9e4-6e16-46a3-aa49-61165141be4b.J3tNdM-oj1ZSTBh4w5hLMceR3PQ",
            "bb8a2eb35860733bb4bb6e1e54d7f398_ssl": "97a3d204-b799-48af-8428-6f13448e8209.l31bd0a4cnmr44HHIYB-yXKtnzA",
            "a132fb583db97a40e2d1989ce2d1f8c7_ssl": "e22bc9c6-9d7e-486f-af16-c612942d08d9.0cgnDgOwlcbtU_Uj9ID8biANfgk",
            "a0248c3bbe9fa0f807f0194308d54d28_ssl": "c3040956-8eaa-4dec-a93f-634c42d3ba1b.M9rXtge7Yyv_jp46YltuitUKfFQ",
            "b270318e049f06359c7cb16a955f16a7_ssl": "fdf742f0-e81a-498a-bbde-f951726ca4bf.POAs2mbOFn5dvmRJv3bXKQhuD4o",
            "b19b601f2e66d61a3a09b8d71e1b4d8f_ssl": "74184516-dacd-4db4-aa6b-237883fd3f28.qoNVip82SasYV8UwYaPfz_pG8m8",
            "819bd279300aefb157fa2c87dc41b246_ssl": "46c677e5-eab1-485a-b96f-666a96fa6b09.RFWl93HNRlnqJ3ckcDDyvrNMntg",
            "17f9cb2039f18c92677e422ffb549f00_ssl": "b3a8e260-eb1d-4c75-bb3d-ba1783d6207a.zpoGrABoIUd7DVXW78Nnry5h5mc",
            "fb20cf0914817c044318207c24a5e1a3_ssl": "4610a7fd-25ce-4c9f-9382-60ec5b2f24ec.iEnsV_hKjqWOhoXWqLCAYCKj4XE",
            "50805df61b64b2ab0cec336733b6a06e_ssl": "40471d9b-796b-428f-baad-4ba8b856ffe7.kB0npF1P_Z8Q7VlJ2lXmh-w2T6Y"
        },
        "Session": [],
        "Server\/Request Data": {
            "USER": "www",
            "HOME": "\/home\/www",
            "HTTP_REFERER": "码",
            "HTTP_PRAGMA": "no-cache",
            "HTTP_COOKIE": "thinkphp_show_page_trace=0|0; locale=zh-cn; 36709c1213f7b62904bd0449e5cc9532_ssl=affd58f5-b999-49cb-a65f-61d36980e8b4.RkLmboEUK5jAnYBRzN6N5svkdHI; 7b423f28fb9dbb33431ad251ec8408cc_ssl=f5c37888-ba61-4508-9b9c-a37d4d36b70e.ZNIXCttMX9XIskUhngaLB13MJeo; 87262c95b25deb0d9458185d23efc85d_ssl=0e770092-2b9e-4ba3-a6e4-84c6dc46c097.jKb2dJ_NUD_5eWqzw0NKsAMCHAg; 7cf654c96b4a588b0e334821bb5943c6_ssl=849ef9e4-6e16-46a3-aa49-61165141be4b.J3tNdM-oj1ZSTBh4w5hLMceR3PQ; bb8a2eb35860733bb4bb6e1e54d7f398_ssl=97a3d204-b799-48af-8428-6f13448e8209.l31bd0a4cnmr44HHIYB-yXKtnzA; a132fb583db97a40e2d1989ce2d1f8c7_ssl=e22bc9c6-9d7e-486f-af16-c612942d08d9.0cgnDgOwlcbtU_Uj9ID8biANfgk; a0248c3bbe9fa0f807f0194308d54d28_ssl=c3040956-8eaa-4dec-a93f-634c42d3ba1b.M9rXtge7Yyv_jp46YltuitUKfFQ; b270318e049f06359c7cb16a955f16a7_ssl=fdf742f0-e81a-498a-bbde-f951726ca4bf.POAs2mbOFn5dvmRJv3bXKQhuD4o; b19b601f2e66d61a3a09b8d71e1b4d8f_ssl=74184516-dacd-4db4-aa6b-237883fd3f28.qoNVip82SasYV8UwYaPfz_pG8m8; 819bd279300aefb157fa2c87dc41b246_ssl=46c677e5-eab1-485a-b96f-666a96fa6b09.RFWl93HNRlnqJ3ckcDDyvrNMntg; 17f9cb2039f18c92677e422ffb549f00_ssl=b3a8e260-eb1d-4c75-bb3d-ba1783d6207a.zpoGrABoIUd7DVXW78Nnry5h5mc; fb20cf0914817c044318207c24a5e1a3_ssl=4610a7fd-25ce-4c9f-9382-60ec5b2f24ec.iEnsV_hKjqWOhoXWqLCAYCKj4XE; 50805df61b64b2ab0cec336733b6a06e_ssl=40471d9b-796b-428f-baad-4ba8b856ffe7.kB0npF1P_Z8Q7VlJ2lXmh-w2T6Y",
            "HTTP_CACHE_CONTROL": "no-cache",
            "HTTP_ACCEPT_LANGUAGE": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
            "HTTP_ACCEPT_ENCODING": "gzip, deflate",
            "HTTP_ACCEPT": "application\/json, text\/plain, *\/*",
            "HTTP_USER_AGENT": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/128.0.0.0 Safari\/537.36 Edg\/128.0.0.0",
            "HTTP_HOST": "码",
            "PATH_INFO": "",
            "REDIRECT_STATUS": "200",
            "SERVER_NAME": "码",
            "SERVER_PORT": "码",
            "SERVER_ADDR": "码",
            "REMOTE_PORT": "6907",
            "REMOTE_ADDR": "码",
            "SERVER_SOFTWARE": "nginx\/1.24.0",
            "GATEWAY_INTERFACE": "CGI\/1.1",
            "REQUEST_SCHEME": "http",
            "SERVER_PROTOCOL": "HTTP\/1.1",
            "DOCUMENT_ROOT": "\/www\/wwwroot\/php\/public",
            "DOCUMENT_URI": "\/index.php",
            "REQUEST_URI": "\/api\/public\/get_system",
            "SCRIPT_NAME": "\/index.php",
            "CONTENT_LENGTH": "",
            "CONTENT_TYPE": "",
            "REQUEST_METHOD": "GET",
            "QUERY_STRING": "s=\/api\/public\/get_system",
            "SCRIPT_FILENAME": "\/www\/wwwroot\/php\/public\/index.php",
            "FCGI_ROLE": "RESPONDER",
            "PHP_SELF": "\/index.php",
            "REQUEST_TIME_FLOAT": 1724744523.714665,
            "REQUEST_TIME": 1724744523
        }
    }
}

**Comment by Yincmewy** [comment]
> > 检查`.env`文件mysql密码是否正确设置
> 
> 是哪里的env文件，以什么格式写入root密码

根目录下的`.env`文件

**Comment by suiyuanccccc** [comment]
> > > 检查`.env`文件mysql密码是否正确设置
> > 
> > 
> > 是哪里的env文件，以什么格式写入root密码
> 
> 根目录下的`.env`文件

![image](https://github.com/user-attachments/assets/e833d96e-d306-446c-9b5c-f150c843b862)
这是我env文件内容，如何加入MySQL root密码

**Comment by Yincmewy** [comment]
> > > > 检查`.env`文件mysql密码是否正确设置
> > > 
> > > 
> > > 是哪里的env文件，以什么格式写入root密码
> > 
> > 根目录下的`.env`文件
> 
> ![image](https://github.com/user-attachments/assets/e833d96e-d306-446c-9b5c-f150c843b862)
> 这是我env文件内容，如何加入MySQL root密码

未安装的话访问`http://域名/#/install`走一遍安装流程
已安装过删除`install.lock`并`清空`数据库重新安装

**Comment by suiyuanccccc** [comment]
> > > > > 检查`.env`文件mysql密码是否正确设置
> > > > 
> > > > 
> > > > 是哪里的env文件，以什么格式写入root密码
> > > 
> > > 
> > > 根目录下的`.env`文件
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/121280968/363033606-e833d96e-d306-446c-9b5c-f150c843b862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTA5ODQsIm5iZiI6MTcyNDk5MDY4NCwicGF0aCI6Ii8xMjEyODA5NjgvMzYzMDMzNjA2LWU4MzNkOTZlLWQzMDYtNDQ2Yy05YjVjLWYxNTBjODQzYjg2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNDA0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWJjOTVjYjIyNjQ0OTRmMzQ5MjU1ZjU3MDJlODgxOTQ1N2ZjOTMwZGJiZjVmMTFlMzZjZDVhYWY4NzZjNDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MLAWvDfrEz2Fw8HBSmkxjrqWQxXg1GKoN-9Io_6BWdI)
> > 这是我env文件内容，如何加入MySQL root密码
> 
> 未安装的话访问`http://域名/#/install`走一遍安装流程 已安装过删除`install.lock`并`清空`数据库重新安装

上个问题已解决，env文件替换时DB部分所有配置文件被替换为空了
![image](https://github.com/user-attachments/assets/9bed8d78-57fc-4f29-b786-92b1090cce6b)
但是现在解决问题后，解析链接任会报这个错

**Comment by Yincmewy** [comment]
请使用最新的发行版搭建

**Comment by Yincmewy** [comment]
> > > > > > 检查`.env`文件mysql密码是否正确设置
> > > > > 
> > > > > 
> > > > > 是哪里的env文件，以什么格式写入root密码
> > > > 
> > > > 
> > > > 根目录下的`.env`文件
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/121280968/363033606-e833d96e-d306-446c-9b5c-f150c843b862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTA5ODQsIm5iZiI6MTcyNDk5MDY4NCwicGF0aCI6Ii8xMjEyODA5NjgvMzYzMDMzNjA2LWU4MzNkOTZlLWQzMDYtNDQ2Yy05YjVjLWYxNTBjODQzYjg2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNDA0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWJjOTVjYjIyNjQ0OTRmMzQ5MjU1ZjU3MDJlODgxOTQ1N2ZjOTMwZGJiZjVmMTFlMzZjZDVhYWY4NzZjNDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MLAWvDfrEz2Fw8HBSmkxjrqWQxXg1GKoN-9Io_6BWdI)
> > > 这是我env文件内容，如何加入MySQL root密码
> > 
> > 未安装的话访问`http://域名/#/install`走一遍安装流程 已安装过删除`install.lock`并`清空`数据库重新安装
> 
> 上个问题已解决，env文件替换时DB部分所有配置文件被替换为空了
> ![image](https://github.com/user-attachments/assets/9bed8d78-57fc-4f29-b786-92b1090cce6b)
> 但是现在解决问题后，解析链接任会报这个错

尝试重试或更换IP

**Comment by suiyuanccccc** [comment]
> 尝试重试或更换IP

这个问题也已经解决，问题成因是cookie冲突。
在安装页面d的cookie如果预先填入账号的BDUSS&STOKEN信息
![image](https://github.com/user-attachments/assets/ab908cf3-cc14-4ad8-9dc3-15152a2a2019)
并且在登陆后的后台添加账号，就会报错。
![image](https://github.com/user-attachments/assets/80d60e29-9b35-400e-bca3-0aee6b229ee1)
解决方案就是安装前不填写cookie或安装后在后台管理中删除cookie中的内容
