### ISSUE TITLE
解析正常但下载问题

### ISSUE THREAD

**Issue by ceoufo** [f4team-cn/f4pan#44]
用的是SVIP账号，可以正常解析，转存也正常。使用web直接下载会下载出来个压缩包，解压出来“结果.txt”“说明.txt”。一个文本里完整的web链接，再复制出来也可以下载。
使用aria2 json rpc 连接是正常的但是无法下载。
![PixPin_2024-08-28_15-52-07](https://github.com/user-attachments/assets/1dbe16c1-b5c4-4506-891c-2d811c9490cb)

**Comment by Yincmewy** [comment]
检查你的aria2端是否设置了密钥

**Comment by ceoufo** [comment]
没有开启密钥，设置了个header OK了

**Comment by huangbh1024** [comment]
> 没有开启密钥，设置了个header OK了

请问一下在什么位置设置header

**Comment by dashouzhang** [comment]
我用完整版搭建的后台登录了s vip账号，设置了cookie，但是不能解析。提示解析失败，请重新连接。
![Uploading mmexport1726826149547.png…]()
