### ISSUE TITLE
网站后台怎么设置，是我设置错误吗一直无法获取链接具体看我的截图

### ISSUE THREAD

**Issue by dashouzhang** [f4team-cn/f4pan#50]
如题：比如后台的cookie，还有账号管理中的账号添加后怎么操作，具体实现原理。是不是和yuantuo的开源代码baidu-wap原理类似。
![1726813203054](https://github.com/user-attachments/assets/1c4abdb6-3e95-4dc3-bf38-8098a1e8194e)

**Comment by Yincmewy** [comment]
请尝试在`.env`文件中开启debug模式打开f12抓取返回数据提交到此议题
