### ISSUE TITLE
必须要开vip吗

### ISSUE THREAD

**Issue by BlueHtml** [f4team-cn/f4pan#51]
你好，点击`下载`按钮，接口返回：`{"code":-1,"message":"获取svip失败, 请重试","data":[]}`。
咱们这个程序 必须要开vip吗？普通账号不能用吗？
我看有 油猴脚本 对于普通用户也是能获取到下载链接的，只是速度特别慢只有20K。。

**Comment by dashouzhang** [comment]
个人猜测没有svip是不行，在解析过程中需要验证svip账户是否可用，然后通过普通账户获取的链接转化成svip账户生成的链接。

**Comment by Yincmewy** [comment]
下个版本会添加非SVIP账户的下载逻辑

**Comment by Yincmewy** [comment]
已在[36961f5](https://github.com/f4team-cn/f4pan/commit/36961f53866e4d0c45d959d27b6a8d1bb341f295)实现
