### ISSUE TITLE
解析报错

### ISSUE THREAD

**Issue by huangbh1024** [f4team-cn/f4pan#53]
{
    "code": 2,
    "message": "Undefined array key \"urls\"",
    "traces": [
        {
            "name": "think\\exception\\ErrorException",
            "file": "\/www\/sites\/download.xxxxx.cn\/index\/app\/controller\/Parse.php",
            "line": 151,
            "code": 2,
            "message": "Undefined array key \"urls\"",
            "trace": [
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/app\/controller\/Parse.php",
                    "line": 151,
                    "function": "appError",
                    "class": "think\\initializer\\Error",
                    "type": "->",
                    "args": [
                        2,
                        "Undefined array key \"urls\"",
                        "\/www\/sites\/download.xxxxx.cn\/index\/app\/controller\/Parse.php",
                        151
                    ]
                },
                {
                    "function": "parseFile",
                    "class": "app\\controller\\Parse",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Container.php",
                    "line": 330,
                    "function": "invokeArgs",
                    "class": "ReflectionMethod",
                    "type": "->",
                    "args": [
                        {},
                        []
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Container.php",
                    "line": 363,
                    "function": "invokeMethod",
                    "class": "think\\Container",
                    "type": "->",
                    "args": [
                        "parseFile",
                        {
                            "req_id": "f4pan_req_id_728b95dc47c09544",
                            "surl": "1hNu9hrMaPevva83LQww1fQ",
                            "pwd": "cei4",
                            "fs_id": "194204088354092",
                            "randsk": "lB3R2HMejalWKUr\/MYhzRWPI+iwfJSibFPR6RUIBEQ8=",
                            "share_id": "64531105081",
                            "uk": "3678156737",
                            "short": "false"
                        },
                        false
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/route\/dispatch\/Callback.php",
                    "line": 27,
                    "function": "invoke",
                    "class": "think\\Container",
                    "type": "->",
                    "args": [
                        [
                            "\\app\\controller\\Parse",
                            "parseFile"
                        ],
                        {
                            "req_id": "f4pan_req_id_728b95dc47c09544",
                            "surl": "1hNu9hrMaPevva83LQww1fQ",
                            "pwd": "cei4",
                            "fs_id": "194204088354092",
                            "randsk": "lB3R2HMejalWKUr\/MYhzRWPI+iwfJSibFPR6RUIBEQ8=",
                            "share_id": "64531105081",
                            "uk": "3678156737",
                            "short": "false"
                        }
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/route\/Dispatch.php",
                    "line": 52,
                    "function": "exec",
                    "class": "think\\route\\dispatch\\Callback",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Route.php",
                    "line": 755,
                    "function": "run",
                    "class": "think\\route\\Dispatch",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 59,
                    "function": "think\\{closure}",
                    "class": "think\\Route",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/app\/middleware\/ParseMiddleware.php",
                    "line": 36,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "function": "handle",
                    "class": "app\\middleware\\ParseMiddleware",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Middleware.php",
                    "line": 134,
                    "function": "call_user_func",
                    "args": [
                        [
                            {},
                            "handle"
                        ],
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/app\/middleware\/VisitRecorder.php",
                    "line": 18,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "function": "handle",
                    "class": "app\\middleware\\VisitRecorder",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Middleware.php",
                    "line": 134,
                    "function": "call_user_func",
                    "args": [
                        [
                            {},
                            "handle"
                        ],
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 66,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Route.php",
                    "line": 754,
                    "function": "then",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Http.php",
                    "line": 208,
                    "function": "dispatch",
                    "class": "think\\Route",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Http.php",
                    "line": 198,
                    "function": "dispatchToRoute",
                    "class": "think\\Http",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 59,
                    "function": "think\\{closure}",
                    "class": "think\\Http",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/middleware\/AllowCrossDomain.php",
                    "line": 61,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "function": "handle",
                    "class": "think\\middleware\\AllowCrossDomain",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Middleware.php",
                    "line": 134,
                    "function": "call_user_func",
                    "args": [
                        [
                            {},
                            "handle"
                        ],
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/think-trace\/src\/TraceDebug.php",
                    "line": 71,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "function": "handle",
                    "class": "think\\trace\\TraceDebug",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Middleware.php",
                    "line": 134,
                    "function": "call_user_func",
                    "args": [
                        [
                            {},
                            "handle"
                        ],
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Pipeline.php",
                    "line": 66,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Http.php",
                    "line": 197,
                    "function": "then",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/vendor\/topthink\/framework\/src\/think\/Http.php",
                    "line": 162,
                    "function": "runWithRequest",
                    "class": "think\\Http",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "\/www\/sites\/download.xxxxx.cn\/index\/public\/index.php",
                    "line": 20,
                    "function": "run",
                    "class": "think\\Http",
                    "type": "->",
                    "args": []
                }
            ],
            "source": {
                "first": 142,
                "source": [
                    "            if (!$to_path){\n",
                    "                $model = new SvipModel();\n",
                    "                $model->updateSvip($id, ['state' =>-1]);\n",
                    "                return responseJson(-1, \"转移文件失败，请检查解析账号可用空间\\n暂不支持解析 解析账号分享的文件\");\n",
                    "            }\n",
                    "        }\n",
                    "        $to_path = rawurlencode($to_path);\n",
                    "        $url = \"https:\/\/pcs.baidu.com\/rest\/2.0\/pcs\/file?method=locatedownload&app_id=250528&path=$to_path&ver=2&time=1676908121&rand=df142c666096ad54f9a9f2de21b02d37d9205722&devuid=O%7C0D9FD9F4941FF7A591BB2A8682D18629\";\n",
                    "        $res = getUrlCurl($url, SystemModel::getUa(), $cookie[0]);\n",
                    "        $realLink = $res['urls'][0]['url'];\n",
                    "        if (str_contains($realLink, \"nd6.baidupcs.com\") && count($res[\"urls\"]) > 1){\n",
                    "            $realLink = $res['urls'][rand(1, count($res[\"urls\"])-1)]['url'];\n",
                    "        }\n",
                    "        preg_match(\"\/size=(\\d+)\/\", $realLink, $pp);\n",
                    "        $filesize = $pp[1];\n",
                    "        preg_match(\"\/&fin=(.+)&bflag\/\", $realLink, $pp);\n",
                    "        $filename = $pp[1];\n",
                    "        $filename = urldecode($filename);\n",
                    "        preg_match(\"\/\\\/file\\\/(.+)\\?\/\", $realLink, $pp);\n"
                ]
            }
        }
    ],
    "datas": [],
    "tables": {
        "GET Data": {
            "req_id": "f4pan_req_id_728b95dc47c09544",
            "surl": "1hNu9hrMaPevva83LQww1fQ",
            "pwd": "cei4",
            "fs_id": "194204088354092",
            "randsk": "lB3R2HMejalWKUr\/MYhzRWPI+iwfJSibFPR6RUIBEQ8=",
            "share_id": "64531105081",
            "uk": "3678156737",
            "short": "false"
        },
        "POST Data": [],
        "Files": null,
        "Cookies": [],
        "Session": [],
        "Server\/Request Data": {
            "HOSTNAME": "d40294326369",
            "PHP_INI_DIR": "\/usr\/local\/etc\/php",
            "SHLVL": "1",
            "HOME": "\/home\/www-data",
            "PHP_LDFLAGS": "-Wl,-O1 -pie",
            "PHP_CFLAGS": "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
            "PHP_VERSION": "8.3.8",
            "COMPOSER_HOME": "\/tmp\/composer",
            "GPG_KEYS": "1198C0117593497A5EC5C199286AF1F9897469DC C28D937575603EB4ABB725861C0779DC5C0A9DE4 AFD8691FDAEDF03BDF6E460563F15A9B715376CA",
            "PHP_CPPFLAGS": "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
            "PHP_ASC_URL": "https:\/\/www.php.net\/distributions\/php-8.3.8.tar.xz.asc",
            "PHP_URL": "https:\/\/www.php.net\/distributions\/php-8.3.8.tar.xz",
            "PATH": "\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin",
            "LD_PRELOAD": "\/usr\/lib\/preloadable_libiconv.so php",
            "PHPIZE_DEPS": "autoconf \t\tdpkg-dev dpkg \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkgconf \t\tre2c",
            "PWD": "\/www",
            "PHP_SHA256": "aea358b56186f943c2bbd350c9005b9359133d47e954cfc561385319ae5bb8d7",
            "USER": "www-data",
            "HTTP_PRIORITY": "u=1, i",
            "HTTP_ACCEPT_LANGUAGE": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7,en-US;q=0.6,ru;q=0.5",
            "HTTP_ACCEPT_ENCODING": "gzip, deflate, br, zstd",
            "HTTP_REFERER": "https:\/\/download.xxxxx.cn\/assets\/parse.831d6c9d.js",
            "HTTP_SEC_FETCH_DEST": "empty",
            "HTTP_SEC_FETCH_MODE": "cors",
            "HTTP_SEC_FETCH_SITE": "same-origin",
            "HTTP_ACCEPT": "application\/json, text\/plain, *\/*",
            "HTTP_USER_AGENT": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/130.0.0.0 Safari\/537.36",
            "HTTP_CACHE_CONTROL": "no-cache",
            "HTTP_PRAGMA": "no-cache",
            "HTTP_HOST": "download.xxxxx.cn",
            "PATH_INFO": "",
            "SCRIPT_FILENAME": "\/www\/sites\/download.xxxxx.cn\/index\/public\/index.php",
            "REDIRECT_STATUS": "200",
            "SERVER_NAME": "download.xxxxx.cn",
            "SERVER_PORT": "443",
            "SERVER_ADDR": "172.19.158.245",
            "REMOTE_PORT": "55118",
            "REMOTE_ADDR": "121.207.145.137",
            "SERVER_SOFTWARE": "nginx",
            "GATEWAY_INTERFACE": "CGI\/1.1",
            "HTTPS": "on",
            "REQUEST_SCHEME": "https",
            "SERVER_PROTOCOL": "HTTP\/2.0",
            "DOCUMENT_ROOT": "\/www\/sites\/download.xxxxx.cn\/index\/public",
            "DOCUMENT_URI": "\/index.php",
            "REQUEST_URI": "\/api\/v1\/parse\/parse_file?req_id=f4pan_req_id_728b95dc47c09544&surl=1hNu9hrMaPevva83LQww1fQ&pwd=cei4&fs_id=194204088354092&randsk=lB3R2HMejalWKUr%2FMYhzRWPI%2BiwfJSibFPR6RUIBEQ8%3D&share_id=64531105081&uk=3678156737&short=false",
            "SCRIPT_NAME": "\/index.php",
            "CONTENT_LENGTH": "",
            "CONTENT_TYPE": "",
            "REQUEST_METHOD": "GET",
            "QUERY_STRING": "s=\/api\/v1\/parse\/parse_file&req_id=f4pan_req_id_728b95dc47c09544&surl=1hNu9hrMaPevva83LQww1fQ&pwd=cei4&fs_id=194204088354092&randsk=lB3R2HMejalWKUr%2FMYhzRWPI%2BiwfJSibFPR6RUIBEQ8%3D&share_id=64531105081&uk=3678156737&short=false",
            "FCGI_ROLE": "RESPONDER",
            "PHP_SELF": "\/index.php",
            "REQUEST_TIME_FLOAT": 1731662008.284169,
            "REQUEST_TIME": 1731662008
        }
    }
}
![image](https://github.com/user-attachments/assets/139323ab-0a1f-4bc1-bacf-99d5bbc72f56)

**Comment by Yincmewy** [comment]
重试，或更换服务器

**Comment by huangbh1024** [comment]
> 请从main分支拉取代码，已修复此问题

可以了
